### ISSUE TITLE
2nd CFP details

### ISSUE THREAD

**Issue by j0ma** [sigturk/sigturk#106]
We need to clarify a few things for the CFP:
- The CFP mentions [sponsorship](https://github.com/sigturk/sigturk.github.io/blob/dd904548176b5f65fca3be15edbe6a68776072fa/content/en/workshop/index.adoc?plain=1#L129) -- is this happening? Let's discuss at the meeting.
- The CFP also mentions a [shared task](https://github.com/sigturk/sigturk.github.io/blob/main/content/en/workshop/index.adoc?plain=1#L125) --  we should remove this language as we're going with just the library development spring / "hack together" event.

This needs to go out today (or ASAP) so let's discuss at today's meeting.

**Comment by j0ma** [comment]
Additional TODOs:
- Send CFP to ACL list again
- Send CFP to university email lists
- Send CFP to other email lists such as corpora-list

**Comment by mehmetoguzderin** [comment]
It could be also sent to independent institutes or foundations usually more associated with linguistics departments. It can increase outreach for the better

**Comment by j0ma** [comment]
Share CFP with
- Turkish groups and profs
- TurkLang conference
- Slack groups
    - `low-resource-languages`
    - `ACL mentorship`
- Telegram groups
    - Turkic Interlingua
    - [Kod Odin](https://t.me/kod_odin)
    - SIGTURK group
- Research institutes affiliated with Turkish universities (as mentioned by @mehmetoguzderin)
- Departmental mailing lists etc.

**Comment by j0ma** [comment]
OK, the [PR](https://github.com/sigturk/sigturk.github.io/pull/24) has been merged. Now all that's left is sending these out to the various groups. I'm going to close this issue and we can continue discussion offline about that process.
