### ISSUE TITLE
Add PC members to Open Review

### ISSUE THREAD

**Issue by d-ataman** [sigturk/sigturk#107]
Send an invitation link to automatically add all members of PC to join the Open Review workshop system.

**Comment by mehmetoguzderin** [comment]
Should we invite as "Reviewers" in OpenReview system?

**Comment by mehmetoguzderin** [comment]
We decided to add as reviewer and use OpenReview email discovery system instead of listing emails internally

**Comment by mehmetoguzderin** [comment]
I had a look at this. Seems like name search does not bring automatically, we should probably invite by email.

**Comment by mehmetoguzderin** [comment]
Done, invited mostly by email.
