### ISSUE TITLE
SouthNLP Symposium 

### ISSUE THREAD

**Issue by defnecirci** [sigturk/sigturk#112]
I'll be attending the [SouthNLP Symposium](https://southnlp.github.io/southnlp2024/index.html#schedule) in Atlanta on April 5, 2024 to present a poster. The symposium's focus on bringing together diverse perspectives in NLP presents a unique opportunity to explore potential collaborations. I hope to invite interested SouthNLP participants to contribute to the future ACL workshop or join our community. If you have specific interests in the symposium's topics or if you're attending and would like to connect, please share your thoughts. I would love to connect.

**Comment by mehmetoguzderin** [comment]
@defnecirci has attended the conference and shared it with us during the meeting. Closing
