### ISSUE TITLE
Workshop: highlight co-location with the ACL Annual Meeting

### ISSUE THREAD

**Issue by varie** [sigturk/sigturk#114]

**Comment by mehmetoguzderin** [comment]
@sigturk/officers-team anybody wanting to volunteer for writing this? @varie did you mean that we should update Workshop page in website so that it is more visible workshop happens together with ACL Conference?

**Comment by varie** [comment]
> @varie did you mean that we should update Workshop page in website so that it is more visible workshop happens together with ACL Conference?

yes

**Comment by j0ma** [comment]
I'll take care of writing this

**Comment by j0ma** [comment]
Cant make todays call but I will get this in today

**Comment by mehmetoguzderin** [comment]
Adding `code` label, thx

**Comment by mehmetoguzderin** [comment]
Done
