### ISSUE TITLE
Workshop: add buttons/links to important parts of the workshop: cfp, programme, committees on the workshop page

### ISSUE THREAD

**Issue by varie** [sigturk/sigturk#115]
We could draw inspiration from other workshops pages.

**Comment by mehmetoguzderin** [comment]
For table of contents of the page, I think just using `:toc` will solve it since our AsciiDoc engine supports it to automatically generate such a navigation material. Please see constitution page, we can add that as a first step, and then detail if need be

**Comment by mehmetoguzderin** [comment]
We discuss this in the meeting. ToC will be sufficient

**Comment by mehmetoguzderin** [comment]
I will fulfill this on the weekend
