### ISSUE TITLE
Reorder contents on the workshop page

### ISSUE THREAD

**Issue by varie** [sigturk/sigturk#125]
We should put more important information closer to the top of the page.

How about something like this?
[Introduction](https://sigturk.com/workshop/#_introduction)
[Important dates](https://sigturk.com/workshop/#_important_dates)
[Topics of interest](https://sigturk.com/workshop/#_topics_of_interest)
["Hack Together" programming event](https://sigturk.com/workshop/#_hack_together_programming_event)
[Submission guidelines](https://sigturk.com/workshop/#_submission_guidelines)
[Invited speakers](https://sigturk.com/workshop/#_invited_speakers)
[Awards](https://sigturk.com/workshop/#_awards)
[Diversity and inclusion statement](https://sigturk.com/workshop/#_diversity_and_inclusion_statement)
[Workshop format](https://sigturk.com/workshop/#_workshop_format)
[Registration](https://sigturk.com/workshop/#_registration)
[Venue](https://sigturk.com/workshop/#_venue)
[Program committee](https://sigturk.com/workshop/#_program_committee)
[Organizing committee](https://sigturk.com/workshop/#_organizing_committee)
[Contact information](https://sigturk.com/workshop/#_contact_information)
[More information](https://sigturk.com/workshop/#_more_information)

**Comment by akoksal** [comment]
Updated, thanks! https://github.com/sigturk/sigturk.github.io/pull/28

**Comment by mehmetoguzderin** [comment]
Great job @akoksal , feel free to close issues at your discretion when you feel it is addressed sufficiently
