### ISSUE TITLE
Move out of SIGTURK-stuff

### ISSUE THREAD

**Issue by mehmetoguzderin** [sigturk/sigturk#22]
There are better names that would align with core guidelines. They should be under consideration for a swift move.

**Comment by mehmetoguzderin** [comment]
I think the channels of GitHub for more-technical-comms, primary mailing list for important announcements, either Matrix or Telegram for real-time communication (already going to be more relax anyways due to the nature of such applications), and Jitsi for meetings is more than plenty already, unless we need to expand curation to enable people from more restrictive networks to partake. Could we just shut this one off instead of even migrating to another one under similar purpose with better naming convention?

Thank you.

**Comment by varie** [comment]
The group was deleted.
