### ISSUE TITLE
Projects tab

### ISSUE THREAD

**Issue by d-ataman** [sigturk/sigturk#30]
It would be good to have a Projects tab to show our ongoing projects.

e.g. We plan to prepare the first formal multilingual general corpus of Turkic languages.

We also plan to have an official venue as part of the ACL to bring all international researchers together.

**Comment by mehmetoguzderin** [comment]
@d-ataman I think this is a great idea, I am tentatively labeling this as discuss so that meetings can incubate ideas a bit more.

**Comment by d-ataman** [comment]
- **Previous Projects**
The Turkic Interlingua (TIL) Multilingual Corpus for Machine Translation was a project conducted by our community that resulted in state-of-the-art pre-trained machine translation systems as well as multi-way parallel training and evaluation resources in 22 Turkic languages. For more details please visit the project GitHub page: https://github.com/turkic-interlingua/til-mt

- **Ongoing Projects**
We are currently establishing standards and methodology for building a large-scale multilingual Turkic Corpus that would have linguistic annotations to be used for developing and evaluating systems for solving natural language processing tasks, such as past-of-speech tagging, named entity recognition, text summarization, and question answering. If you are interested in contributing to this project please feel free to get in touch with us.

- **Future plans**
As a rapidly growing special interest group we are aiming to start holding official meetings starting from 2023 to promote and accelerate progress in computational linguistics of Turkic languages. We hope to see anyone interested in Turkic languages to be involved and participate in our future workshops. More details will be available through our website and newsletters.

**Comment by mehmetoguzderin** [comment]
@d-ataman thanks for the initial version.

@mammadhajili @mirzakhalov @varie @j0ma PTAL, if all feels comfortable, I can create a PR text with iterated version!~
