### ISSUE TITLE
Typo in emails on the People tab on sigturk.github.io

### ISSUE THREAD

**Issue by varie** [sigturk/sigturk#34]
The president's email should be: sigturk.president@gmail.com instead of sigturk-president@gmail.com.
The secretary's email should be: sigturk.secretary@gmail.com instead of sigturk-secretary@gmail.com.

Link: https://sigturk.github.io/people/

**Comment by mehmetoguzderin** [comment]
@varie Thank you so much for bringing this to the SIG's attention.

Could you check https://github.com/sigturk/sigturk.github.io/pull/3 PR?

Thanks!
