### ISSUE TITLE
Update officers section

### ISSUE THREAD

**Issue by mehmetoguzderin** [sigturk/sigturk#45]
Due to matching number of nominations for the election, it was decided that the individuals listed are appointed as the governing body. Website should match it.

See the listing:
https://groups.google.com/g/sigturk/c/jPAcrOs3jrY

**Comment by varie** [comment]
People who attended the meeting on 19th of December 2022 (@jonorthwash, @mammadhajili, @mehmetoguzderin, @varie) agreed with that.

The president:
Duygu Ataman

The secretary:
Sardana Ivanova

Officers:
Mehmet Oguz Derin
Mammad Hajili
Jonne Sälevä
Jamshidbek Mirzakhalov
