### ISSUE TITLE
Welcoming Non-Anglophone People

### ISSUE THREAD

**Issue by mehmetoguzderin** [sigturk/sigturk#6]
Since the group focuses on Turkic languages, it is natural that there will be many non-Anglophone people interested in partaking in discussions and developments. Therefore, the group can provide various comfort to such people during meetings and for the technical content.

During the meetings, I would suggest prioritizing the chat section and any message there as if they have a voice. The group should embrace it for people to ask for a word they did not catch properly and prevent frowning in any case.

I would like to point out that the fact that there is a traceable issue, PR, and review process helps with welcoming since it avoids situations like "oh, we discussed, we got a Markdown site ready, and somebody told about something, and that is irrelevant voice now" where non-loudest-voice gets pushed aside.

The group can adopt various style guidelines for the codes and documents, including technical writing ones, and maintain terminology and vocabulary glossaries to help anybody resolve their reading at their own pace.

**Comment by d-ataman** [comment]
@d-ataman @varie

**Comment by mehmetoguzderin** [comment]
I think we can consider this to be partially close with CoEC and move to more granular suggestions over time
