### ISSUE TITLE
Constitutional amendment: Increase number of officers to 5

### ISSUE THREAD

**Issue by j0ma** [sigturk/sigturk#65]
Currently the constitution states that we have **four** officers in addition to the Secretary and President:

> The elected officers of the SIG shall consist of a President, a Secretary and up to 4 other officers, constituting the Executive Committee. The President and Secretary shall be members in good standing of the ACL.

Since we've discussed that adding another officer position might be desirable, I move to change the wording above from _up to 4_ to _up to 5_.

We need a total of 5 people to support the petition -- please indicate your support below :slightly_smiling_face:

**Comment by varie** [comment]
I support the petition! :)

**Comment by mehmetoguzderin** [comment]
Me three

**Comment by azizamirsaidova** [comment]
I support

**Comment by j0ma** [comment]
awesome thanks everyone! one more to go!

**Comment by mirzakhalov** [comment]
Hi! I support the petition too :)

**Comment by j0ma** [comment]
Perfect! We'll send out a proper amendment motion over the mailing list so all members can see it.

**Comment by mehmetoguzderin** [comment]
@j0ma TYVM for all your efforts, I express my kindest appreciation. It matters a lot.

**Comment by mammadhajili** [comment]
Hey. I support the petition too.

**Comment by j0ma** [comment]
Motion email sent to mailing list. Please vote when the time comes and suggest further motions/amendments in the meantime (only 3 persons needed).

**Comment by mehmetoguzderin** [comment]
Well-done!
