### ISSUE TITLE
How to do the voting for May Constitutional Amendment

### ISSUE THREAD

**Issue by mehmetoguzderin** [sigturk/sigturk#68]
I think we can do email voting like last time.

**Comment by j0ma** [comment]
that sounds good to me, maybe require that they include a specific string in the subject line so we can grep for all the votes as needed. 

one potential drawback is that this isn't anonymous and we can see who cast which vote.

**Comment by d-ataman** [comment]
I confirm we can announce the modified information in the constitution by e-mail to the members in the mail list, and officially call for votes. After the voting period we can insert the changes. We can use three weeks as voting period.
