### ISSUE TITLE
Inviting and Welcoming Representative People

### ISSUE THREAD

**Issue by mehmetoguzderin** [sigturk/sigturk#7]
This group can be a bridge for representative people of non-computational or non-NLP backgrounds to contribute their expertise or effort toward creating more stable, interoperable, and internally-consistent modules for Turkic languages. The study of these languages is improving in all aspects. Still, there is a lack of communication of state of the art for varying concepts emerging from alternative concerns, including copular constructs. To invite and welcome people who can help provide access to material and provide communication with their experts, I would argue that SIGTURK should do more than minimal to foster such a non-existing environment.

I raise a concern that I find primary in a separate issue. Otherwise, this issue can host the dialogue for the codification of this title. The additional topic of go-to materials for expressing a purpose (towards experts, local communities, etc., to morally incentivize people) to get involved in this intersection and development can be an issue of its own (not to say this issue should not spawn any other).

**Comment by d-ataman** [comment]
Can we please close older issues to allow faster review of important issues on a regular basis. This will be addressed in code of conduct.

**Comment by mehmetoguzderin** [comment]
@d-ataman Thank you for your help. I'm reopening in the interest of making this issue close automatically by the relevant PR, a PR can automatically close multiple issues, which increases the responsible tracing of issues and what happened to them without huge hops
